INSERT INTO INGREDIENTS (ID, NAME, QUANTITY) VALUES(1, "Mint", 200);
INSERT INTO INGREDIENTS (ID, NAME, QUANTITY) VALUES(2, "Parsley", 500);
INSERT INTO INGREDIENTS (ID, NAME, QUANTITY) VALUES(3, "Panko Breadcrumbs", 1000);
